app/Http/routes.php
<?php
use App\Employee;

use App\Location;

use App\Equipment;

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


Route::auth();

Route::get('/', 'HomeController@index');
Route::resource('/employees', 'EmployeesController');
Route::resource('/equipment', 'EquipmentsController');
Route::resource('/equipmentOwner', 'EquipmentOwnersController');
Route::resource('/locations', 'LocationsController');


Route::get('/locations', 'LocationsController@index')->middleware('auth');
//Route::get('/locations/create', 'LocationsController@create')->middleware('auth');
//Route::get('locations/{locations} ', 'LocationsController@update')->middleware('auth');
//Route::get('locations/{locations}/edit ', 'LocationsController@edit')->middleware('auth');
//Route::get('locations/{locations} ', 'LocationsController@destroy')->middleware('auth');

Route::get('/employees', 'EmployeesController@index')->middleware('auth');
//Route::get('/employees/create', 'EmployeesController@create')->middleware('auth');
//Route::get('/employees/{employees}', 'EmployeesController@update')->middleware('auth');
//Route::get('/employees/{employees}', 'EmployeesController@update')->middleware('auth');
//Route::get('/employees/{employees}', 'EmployeesController@destroy')->middleware('auth');
//Route::get('/employees/{employees}/edit', 'EmployeesController@edit')->middleware('auth');


Route::get('/equipment', 'EquipmentsController@index')->middleware('auth');


Route::get('/equipmentOwner', 'EquipmentOwnersController@index')->middleware('auth');

//Route::get('/equipmentOwner/create', 'EquipmentOwnersController@edit')->middleware('IsAdmin');

Route::resource('/users', 'UsersController');

app/EquipmentOwner.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class EquipmentOwner extends Model
{
    protected $fillable= ['name', 'company', 'comment'];
}

app/Http/Controllers/EquipmentOwnersController.php
<?php

namespace App\Http\Controllers;

use App\Equipment;
use App\EquipmentOwner;
use Illuminate\Http\Request;
use App\Http\Requests;

class EquipmentOwnersController extends Controller
{

    public function index()
    {
        $equipmentOwners = EquipmentOwner::all();
        return view('equipmentOwner.index', compact('equipmentOwners'));
    }


    public function create()
    {
        return view('equipmentOwner.create');
    }


    public function store(Request $request)
    {
        $this->validate($request, [
            'name'=>'required|max:50',
            'company'=>'required|max:50',
            'comment'=>'required|max:500'
        ]);

        EquipmentOwner::create($request->all()); //sprema lokaciju u bazu

        return redirect('/equipmentOwner');
    }


    public function show($id)
    {
        //
    }


    public function edit($id)
    {
        $equipmentOwner = EquipmentOwner::findOrFail($id);

        return view('equipmentOwner.edit', compact('equipmentOwner'));
    }

    public function update(Request $request, $id)
    {
        $equipmentOwner = EquipmentOwner::findOrFail($id);

        $equipmentOwner->update($request->all());
        return redirect('equipmentOwner');
    }

    public function destroy($id)
    {
        $equipmentOwner = EquipmentOwner::findOrFail($id);

        $equipmentOwner->delete();

        return redirect('equipmentOwner');
    }
}

resources/views/equipmentOwner/create.blade.php
@extends ('layouts.admin')

@section('content')
    <div class="col-md-6 col-md-offset-3">
        <div class="box-body">
            <div class="panel panel-default">
                <div class="panel-heading"></div>
                <div class="panel-body">
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    {!! Form::open(['method'=>'POST', 'action'=>'EquipmentOwnersController@store', ]) !!}
                    {{csrf_field()}}

                    {!! Form::label('name', 'Ime vlasnika opreme') !!}
                    {!! Form::text('name', null, ['class'=>'form-control']) !!}

                    {!! Form::label('company', 'Naziv tvrtke') !!}
                    {!! Form::text('company', null, ['class'=>'form-control']) !!}

                    <div class="form-group">

                        {!! Form::label('comment', 'Komentar') !!}
                        {!! Form::text('comment', null, ['class'=>'form-control']) !!}

                    </div>

                    {!! Form::submit('Dodaj', ['class'=>'btn btn-primary center-block btn-style']) !!}

                    {!! Form::close() !!}

                </div>
            </div>
        </div>
    </div>


@endsection('footer')

resources/views/equipmentOwner/edit.blade.php
@extends ('layouts.admin')

@section('content')

    <div class="col-md-6 col-md-offset-3">
        <div class="box-body">
            <div class="panel panel-default">
                <div class="panel-heading"></div>
                <div class="panel-body">

                    {!! Form::model($equipmentOwner,['method'=>'PATCH', 'action'=>['EquipmentOwnersController@update', $equipmentOwner->id]]) !!}
                    {{csrf_field()}}

                    {!! Form::label('name', 'Ime vlasnika opreme') !!}
                    {!! Form::text('name', null, ['class'=>'form-control']) !!}

                    {!! Form::label('company', 'Naziv tvrtke') !!}
                    {!! Form::text('company', null, ['class'=>'form-control']) !!}

                    {!! Form::label('comment', 'Komentar') !!}
                    {!! Form::text('comment', null, ['class'=>'form-control form-group']) !!}

                    {!! Form::submit('Pohrani promjene', ['class'=>'btn btn-primary center-block btn-style']) !!}

                    {!! Form::close() !!}

                    {!! Form::open(['method'=>'DELETE', 'action'=>['EquipmentOwnersController@destroy', $equipmentOwner->id]]) !!}
                    {{csrf_field()}}

                    {!! Form::submit('Ukloni vlasnika opreme', ['class'=>'btn btn-danger pull-right']) !!}

                    {!! Form::close() !!}

                </div>
            </div>
        </div>
    </div>

@endsection('footer')

resources/views/equipmentOwner/index.blade.php
@extends ('layouts.admin')

@section('content')
    <div class="col-md-10 col-md-offset-1">
        <div class="box-body">
            <div class="panel panel-default">
                <div class="panel-heading">Vlasnik opreme</div>
                <div class="panel-body">
                <table class="table table-bordered table-hover dtable">
        <thead align="center">
        <tr>
            <th>Ime vlasnika opreme</th>
            <th>Naziv tvrtke</th>
            <th>Komentar</th>
            @if(Auth::user()->role == "Administrator")
                <th></th>
                <th></th>
            @endif
        </tr>
        </thead>
        <tbody>

        @foreach($equipmentOwners as $equipmentOwner)
            <tr>
                <td>{{$equipmentOwner->name}}</td>
                <td>{{$equipmentOwner->company}}</td>
                <td>{{$equipmentOwner->comment}}</td>
                @if(Auth::user()->role == "Administrator")
                    <td><div class="text-center" ><a href="{{route('equipmentOwner.edit', $equipmentOwner->id)}}"><i class="glyphicon glyphicon-edit"></i></a></div></td>
                    <td><div class="text-center" ><a href="{{route('equipmentOwner.destroy', $equipmentOwner->id)}}"><i class="glyphicon glyphicon-trash"></i></a></div></td>
                @endif
            </tr>
        @endforeach

        </tbody>
    </table>
                    @if(Auth::user()->role == "Administrator")
                        <button type="submit" class="btn btn-primary center-block btn-style"><a style="color: white" href="{{route('equipmentOwner.create')}}">Dodaj vlasnika opreme</a></button>
                    @endif
            </div>
        </div>
    </div>
    </div>



@stop

@extends('layouts.footer')