app/Http/routes.php
<?php
use App\Employee;

use App\Location;

use App\Equipment;

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


Route::auth();

Route::get('/', 'HomeController@index');
Route::resource('/employees', 'EmployeesController');
Route::resource('/equipment', 'EquipmentsController');
Route::resource('/equipmentOwner', 'EquipmentOwnersController');
Route::resource('/locations', 'LocationsController');


Route::get('/locations', 'LocationsController@index')->middleware('auth');
//Route::get('/locations/create', 'LocationsController@create')->middleware('auth');
//Route::get('locations/{locations} ', 'LocationsController@update')->middleware('auth');
//Route::get('locations/{locations}/edit ', 'LocationsController@edit')->middleware('auth');
//Route::get('locations/{locations} ', 'LocationsController@destroy')->middleware('auth');

Route::get('/employees', 'EmployeesController@index')->middleware('auth');
//Route::get('/employees/create', 'EmployeesController@create')->middleware('auth');
//Route::get('/employees/{employees}', 'EmployeesController@update')->middleware('auth');
//Route::get('/employees/{employees}', 'EmployeesController@update')->middleware('auth');
//Route::get('/employees/{employees}', 'EmployeesController@destroy')->middleware('auth');
//Route::get('/employees/{employees}/edit', 'EmployeesController@edit')->middleware('auth');


Route::get('/equipment', 'EquipmentsController@index')->middleware('auth');


Route::get('/equipmentOwner', 'EquipmentOwnersController@index')->middleware('auth');

//Route::get('/equipmentOwner/create', 'EquipmentOwnersController@edit')->middleware('IsAdmin');

Route::resource('/users', 'UsersController');

app/Equipment.php
<?php

namespace App;
use App\Location;
use App\EquipmentOwner;
use Illuminate\Database\Eloquent\Model;

class Equipment extends Model
{
    protected $fillable = [

        'name',
        'serial_number',
        'pn_number',
        'model',
        'comment',
        'location_id',
        'equipment_owner_id'

    ];

    public function location(){

        return $this->belongsTo('App\Location');

    }

    public function equipmentOwner(){

        return $this->belongsTo('App\EquipmentOwner');

    }
}

app/Http/Controllers/EquipmentsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use LaravelQRCode\Facades\QRCode;
use App\Http\Requests;
use App\Equipment;
use App\Location;
use App\EquipmentOwner;

class EquipmentsController extends Controller
{

    public function index()
    {
        $equipments = Equipment::all();
        return view('equipment.index', compact('equipments'));
    }


    public function create()
    {
        $locations = Location::all(['id', 'name']);
        $equipmentOwners = EquipmentOwner::all(['id', 'name']);

        return view('equipment.create', compact('locations', 'equipmentOwners'));
    }


    public function store(Request $request)
    {

        $input = $request->all();

        $this->validate($request, [
            'name'=>'required|max:50',
            'pn_number' =>'required|max:20',
            'serial_number' =>'required|max:20',
            'model' =>'required|max:50',
            'comment' =>'required|max:500',
        ]);

       $equipment = Equipment::create($input);


        $file = 'qrcodes/'.$equipment->id.'.png';


        QRCode::text("Naziv opreme:  $equipment->name | PN broj: $equipment->pn_number | Serijski broj: $equipment->serial_number | Model opreme: $equipment->model")
            ->setSize(4)
            ->setMargin(2)
            ->setOutfile($file)
            ->png();

        $input['qrcode_path'] = $file;


         Equipment::where('id', $equipment->id)->update(['qrcode_path' =>  $input['qrcode_path']]);


        return redirect('/equipment');
    }


    public function show($id)
    {
        $equipment = Equipment::findOrFail($id);
        $locations = Location::all();
        $equipmentOwners = EquipmentOwner::all();

        return view('equipment.show', compact('equipment', 'locations', 'equipmentOwners'));
    }


    public function edit($id)
    {
        $equipment = Equipment::findOrFail($id);
        $locations = Location::all();
        $equipmentOwners = EquipmentOwner::all();

        return view('equipment.edit', compact('equipment', 'locations', 'equipmentOwners'));
    }


    public function update(Request $request, $id)
    {
        $equipment = Equipment::findOrFail($id);

        $equipment->update($request->all());
        return redirect('equipment');
    }


    public function destroy($id)
    {
        $equipment = Equipment::findOrFail($id);

        $equipment->delete();

        return redirect('equipment');
    }
}

resources/views/equipment/create.blade.php
@extends ('layouts.admin')

@section('content')

    <div class="col-md-8 col-md-offset-2">
        <div class="box-body">
            <div class="panel panel-default">
                <div class="panel-heading"></div>
                <div class="panel-body">
                    {!! Form::open(['method'=>'POST', 'action'=>'EquipmentsController@store']) !!}
                    {{csrf_field()}}

                    {!! Form::label('name', 'Naziv opreme') !!}
                    {!! Form::text('name', null, ['class'=>'form-control']) !!}

                    <div class="form-group">
                        {!! Form::Label('name', 'Lokacija') !!}
                        <select class="form-control" name="location_id">
                            @foreach($locations as $location)
                                <option value="{{$location->id}}">{{$location->name}}</option>
                            @endforeach
                        </select>
                    </div>

                    <div class="form-group">
                        {!! Form::Label('name', 'Vlasnik opreme') !!}
                        <select class="form-control" name="equipment_owner_id">
                            @foreach($equipmentOwners as $equipmentOwner)
                                <option value="{{$equipmentOwner->id}}">{{$equipmentOwner->name}}</option>
                            @endforeach
                        </select>
                    </div>

                    {!! Form::label('pn_number', 'PN broj') !!}
                    {!! Form::text('pn_number', null, ['class'=>'form-control']) !!}

                    {!! Form::label('serial_number', 'Serijski broj') !!}
                    {!! Form::text('serial_number', null, ['class'=>'form-control']) !!}

                    {!! Form::label('model', 'Model opreme') !!}
                    {!! Form::text('model', null, ['class'=>'form-control']) !!}

                    <div class="form-group">

                        {!! Form::label('comment', 'Komentar') !!}
                        {!! Form::text('comment', null, ['class'=>'form-control']) !!}

                    </div>

                    {!! Form::submit('Dodaj', ['class'=>'btn btn-primary center-block btn-style']) !!}

                    {!! Form::close() !!}

                </div>
            </div>
        </div>
    </div>



@endsection('footer')

resources/views/equipment/edit.blade.php
@extends ('layouts.admin')

@section('content')

    <div class="col-md-6 col-md-offset-3">
        <div class="box-body">
            <div class="panel panel-default">
                <div class="panel-heading"></div>
                <div class="panel-body">

                    {!! Form::model($equipment,['method'=>'PATCH', 'action'=>['EquipmentsController@update', $equipment->id]]) !!}
                    {{csrf_field()}}

                    {!! Form::label('name', 'Naziv opreme') !!}

                    {!! Form::text('name', null, ['class'=>'form-control']) !!}

                    <div class="form-group">
                        {!! Form::Label('name', 'Lokacija') !!}
                        <select class="form-control" name="location_id">
                            @foreach($locations as $location)
                                <option value="{{$location->id}}"
                                @if ($equipment->location->name ==$location->name )
                                    {{ 'selected' }}
                                        @endif
                                >{{$location->name ?? '*Lokacija uklonjena'}}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        {!! Form::Label('name', 'Vlasnik opreme') !!}
                        <select class="form-control" name="equipment_owner_id">
                            @foreach($equipmentOwners as $equipmentOwner)
                                <option value="{{$equipmentOwner->id}}"
                                @if ($equipment->equipmentOwner->name ==$equipmentOwner->name )
                                    {{ 'selected' }}
                                        @endif
                                >{{$equipmentOwner->name ?? '*Vlasnik opreme uklonjen'}}</option>
                            @endforeach
                        </select>
                    </div>

                    {!! Form::label('pn_number', 'PN broj') !!}
                    {!! Form::text('pn_number', null, ['class'=>'form-control']) !!}

                    {!! Form::label('serial_number', 'Serijski broj') !!}
                    {!! Form::text('serial_number', null, ['class'=>'form-control']) !!}

                    {!! Form::label('model', 'Model opreme') !!}
                    {!! Form::text('model', null, ['class'=>'form-control']) !!}

                    {!! Form::label('comment', 'Komentar') !!}
                    {!! Form::text('comment', null, ['class'=>'form-control form-group']) !!}

                    {!! Form::submit('Pohrani promjene', ['class'=>'btn btn-primary center-block btn-style']) !!}

                    {!! Form::close() !!}

                    {!! Form::open(['method'=>'DELETE', 'action'=>['EquipmentsController@destroy', $equipment->id]]) !!}
                    {{csrf_field()}}

                    {!! Form::submit('Ukloni opremu', ['class'=>'btn btn-danger pull-right']) !!}

                    {!! Form::close() !!}

                </div>
            </div>
        </div>
    </div>

@endsection('footer')
<style>
    .col-centered{
        float: none;
        margin: 0 auto;
    }

</style>

resources/views/equipment/index.blade.php
@extends ('layouts.admin')

@section('content')

    <div class="col-md-10 col-md-offset-1">
        <div class="box-body">
            <div class="panel panel-default">
                <div class="panel-heading">Oprema</div>
                <div class="panel-body">
                    <table class="table table-bordered table-hover dtable">
                        <thead align="center">
                        <tr>
                            <th>Naziv opreme</th>
                            <th>Lokacija opreme</th>
                            <th>Vlasnik opreme</th>
                            <th>PN broj</th>
                            <th>Serijski broj</th>
                            <th>Model</th>
                            <th>Komentar</th>
                            @if(Auth::user()->role == "Administrator")
                                <th></th>
                                <th></th> <th></th>
                            @endif
                        </tr>
                        </thead>
                        <tbody>

                        @foreach($equipments as $equipment)
                            <tr>
                                <td>{{$equipment->name}}</td>
                                <td>{{$equipment->location->name ?? '*Lokacija uklonjena'}}</td>
                                <td>{{$equipment->equipmentOwner->name ?? '*Vlasnik opreme uklonjen'}}</td>
                                <td>{{$equipment->pn_number}}</td>
                                <td>{{$equipment->serial_number}}</td>
                                <td>{{$equipment->model}}</td>
                                <td>{{$equipment->comment}}</td>
                                @if(Auth::user()->role == "Administrator")
                                     <td><div class="text-center"><a href="{{route('equipment.show', $equipment->id)}}"><i class="glyphicon glyphicon-eye-open"></i></a></div></td>
                                     <td><div class="text-center" ><a href="{{route('equipment.edit', $equipment->id)}}"><i class="glyphicon glyphicon-edit"></i></a></div></td>
                                    <td><div class="text-center" ><a href="{{route('equipment.destroy', $equipment->id)}}"><i class="glyphicon glyphicon-trash"></i></a></div></td>
                                @endif
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                    @if(Auth::user()->role == "Administrator")
                        <button type="submit" class="btn btn-primary center-block btn-style"><a style="color: white"
                                                                                                href="{{route('equipment.create')}}">Dodaj opremu</a></button>
                    @endif
                </div>

            </div>

        </div>
    </div>


@stop

@extends('layouts.footer')

resources/views/equipment/show.blade.php
@extends ('layouts.admin')

@section('content')

    <div class="col-md-8 col-md-offset-2">
        <div class="box-body">
            <div class="panel panel-default">
                <div class="panel-heading"></div>
                <div class="panel-body">

                    {!! Form::model($equipment,['method'=>'PATCH', 'action'=>['EquipmentsController@update', $equipment->id]]) !!}
                    {{csrf_field()}}

                    {!! Form::label('name', 'Naziv opreme') !!}

                    {!! Form::text('name', null, ['class'=>'form-control']) !!}

                    <div class="form-group">
                        {!! Form::Label('name', 'Lokacija') !!}
                        <select class="form-control" name="location_id">
                            @foreach($locations as $location)
                                <option value="{{$location->id}}"
                                @if ($equipment->location->name ==$location->name || $location->name =='*Lokacija uklonjena' )
                                    {{ 'selected' }}
                                        @endif
                                >{{$location->name ?? '*Lokacija uklonjena'}}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        {!! Form::Label('name', 'Vlasnik opreme') !!}
                        <select class="form-control" name="equipment_owner_id">
                            @foreach($equipmentOwners as $equipmentOwner)
                                <option value="{{$equipmentOwner->id}}"
                                @if ($equipment->equipmentOwner->name ==$equipmentOwner->name)
                                    {{ 'selected' }}
                                        @endif
                                >{{$equipmentOwner->name ?? '*Vlasnik opreme uklonjen'}}</option>
                            @endforeach
                        </select>
                    </div>

                    {!! Form::label('pn_number', 'PN broj') !!}
                    {!! Form::text('pn_number', null, ['class'=>'form-control']) !!}

                    {!! Form::label('serial_number', 'Serijski broj') !!}
                    {!! Form::text('serial_number', null, ['class'=>'form-control']) !!}

                    {!! Form::label('model', 'Model opreme') !!}
                    {!! Form::text('model', null, ['class'=>'form-control']) !!}

                    {!! Form::label('comment', 'Komentar') !!}
                    {!! Form::text('comment', null, ['class'=>'form-control form-group']) !!}

                    {!! Form::label('qrcode_path', 'QR KOD') !!}
                    <br>
                    <img  src="{{asset( $equipment->qrcode_path)}}" width="150px" alt="">

                    {!! Form::close() !!}


                </div>
            </div>
        </div>
    </div>

@endsection('footer')