app/Http/routes.php
<?php
use App\Employee;

use App\Location;

use App\Equipment;

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


Route::auth();

Route::get('/', 'HomeController@index');
Route::resource('/employees', 'EmployeesController');
Route::resource('/equipment', 'EquipmentsController');
Route::resource('/equipmentOwner', 'EquipmentOwnersController');
Route::resource('/locations', 'LocationsController');


Route::get('/locations', 'LocationsController@index')->middleware('auth');
//Route::get('/locations/create', 'LocationsController@create')->middleware('auth');
//Route::get('locations/{locations} ', 'LocationsController@update')->middleware('auth');
//Route::get('locations/{locations}/edit ', 'LocationsController@edit')->middleware('auth');
//Route::get('locations/{locations} ', 'LocationsController@destroy')->middleware('auth');

Route::get('/employees', 'EmployeesController@index')->middleware('auth');
//Route::get('/employees/create', 'EmployeesController@create')->middleware('auth');
//Route::get('/employees/{employees}', 'EmployeesController@update')->middleware('auth');
//Route::get('/employees/{employees}', 'EmployeesController@update')->middleware('auth');
//Route::get('/employees/{employees}', 'EmployeesController@destroy')->middleware('auth');
//Route::get('/employees/{employees}/edit', 'EmployeesController@edit')->middleware('auth');


Route::get('/equipment', 'EquipmentsController@index')->middleware('auth');


Route::get('/equipmentOwner', 'EquipmentOwnersController@index')->middleware('auth');

//Route::get('/equipmentOwner/create', 'EquipmentOwnersController@edit')->middleware('IsAdmin');

Route::resource('/users', 'UsersController');

app/Location.php
<?php

namespace App;
use App\Employee;
use Illuminate\Database\Eloquent\Model;

class Location extends Model
{
    protected $fillable= ['name', 'number_of_employees'];

    public function employees(){

        return $this->hasMany('App\Employee', 'employee_id');

    }


}

app/Http/Controllers/LocationsController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;

use App\Http\Requests;

use App\Location as Location;

class LocationsController extends Controller
{

    /*public function __construct() {
        $this->middleware('IsAdmin', ['except'=>['index_location']
        ]);
    }*/




    public function index()
    {
       $users = User::all();
       $locations = Location::all();
        return view('locations.index', compact('locations', 'users'));
    }


    public function create()
    {
        return view('locations.create');
    }


    public function store(Request $request)
    {
        $this->validate($request, [
            'name'=>'required|max:50',
            'number_of_employees'=>'required'
        ]);


        Location::create($request->all()); //sprema lokaciju u bazu

        return redirect('/locations');

    }


    public function show($id) //nije potrebno za sad
    {
        $location = Location::findOrFail($id);

        return view('locations.show', compact('location'));
    }


    public function edit($id)
    {
        $location = Location::findOrFail($id);

        return view('locations.edit', compact('location'));
    }


    public function update(Request $request, $id)
    {
        $location = Location::findOrFail($id);

        $location->update($request->all());
        return redirect('locations');
    }


    public function destroy($id)
    {
        $location = Location::findOrFail($id);

        $location->delete();

        return redirect('locations');
    }

}

resources/views/locations/create.blade.php
@extends ('layouts.admin')

@section('content')
    <div class="col-md-6 col-md-offset-3">
        <div class="box-body">
            <div class="panel panel-default">
                <div class="panel-heading"></div>
                <div class="panel-body">
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif

                    {!! Form::open(['method'=>'POST', 'action'=>'LocationsController@store', ]) !!}
                    {{csrf_field()}}

                    {!! Form::label('name', 'Ime lokacije') !!}
                    {!! Form::text('name', null, ['class'=>'form-control']) !!}

                    {!! Form::label('number_of_employees', 'Broj zaposlenika') !!}
                    {!! Form::text('number_of_employees', null, ['class'=>'form-control form-group']) !!}

                    {!! Form::submit('Dodaj', ['class'=>'btn btn-primary center-block btn-style']) !!}

                    {!! Form::close() !!}

                </div>
            </div>
        </div>

    </div>

@endsection('footer')

resources/views/locations/edit.blade.php
@extends ('layouts.admin')

@section('content')
    <div class="col-md-6 col-md-offset-3">
        <div class="box-body">
            <div class="panel panel-default">
                <div class="panel-heading"></div>
                <div class="panel-body">

                    {!! Form::model($location,['method'=>'PATCH', 'action'=>['LocationsController@update', $location->id]]) !!}
                    {{csrf_field()}}

                    {!! Form::label('name', 'Ime lokacije') !!}
                    {!! Form::text('name', null, ['class'=>'form-control']) !!}

                    {!! Form::label('number_of_employees', 'Broj zaposlenika') !!}

                    {!! Form::text('number_of_employees', null, ['class'=>'form-control form-group']) !!}

                    {!! Form::submit('Pohrani promjene', ['class'=>'btn btn-primary center-block btn-style']) !!}

                    {!! Form::close() !!}

                    {!! Form::open(['method'=>'DELETE', 'action'=>['LocationsController@destroy', $location->id]]) !!}
                    {{csrf_field()}}

                    {!! Form::submit('Ukloni lokaciju', ['class'=>'btn btn-danger pull-right']) !!}


                    {!! Form::close() !!}

                </div>
            </div>
        </div>
    </div>

@endsection('footer')

resources/views/locations/index.blade.php
@extends ('layouts.admin')

@section('content')

    <div class="col-md-10 col-md-offset-1">
        <div class="box-body">
            <div class="panel panel-default">
                <div class="panel-heading">Lokacija</div>
                <div class="panel-body">
                    <table class="table table-bordered table-hover dtable">
                        <thead align="center">
                        <tr>
                            <th>Naziv lokacije</th>
                            <th>Broj zaposlenika</th>

                            @if(Auth::user()->role == "Administrator")
                                <th></th>
                                <th></th>
                            @endif
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($locations as $location)
                            <tr>
                                <td>{{$location->name}}</td>
                                <td>{{$location->number_of_employees}}</td>
                                @if(Auth::user()->role == "Administrator")
                                    <td><div class="text-center" ><a href="{{route('locations.edit', $location->id)}}"><i class="glyphicon glyphicon-edit"></i></a></div></td>
                                    <td><div class="text-center" ><a href="{{route('locations.destroy', $location->id)}}"><i class="glyphicon glyphicon-trash"></i></a></div></td>
                                @endif
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                    @if(Auth::user()->role == "Administrator")
                        <button type="submit" class="btn btn-primary center-block btn-style"><a style="color: white"
                                                                                                href="{{route('locations.create')}}">Dodaj lokaciju</a></button>
                    @endif
                </div>
            </div>
        </div>
    </div>



@stop


@extends ('layouts.footer')

resources/views/locations/show.blade.php
@extends ('layouts.app')

@section('content')

    <li>{{$location->name}}</li>
    <li>{{$location->number_of_employees}}</li>




@endsection('footer')