app/Http/routes.php
<?php
use App\Employee;

use App\Location;

use App\Equipment;

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


Route::auth();

Route::get('/', 'HomeController@index');
Route::resource('/employees', 'EmployeesController');
Route::resource('/equipment', 'EquipmentsController');
Route::resource('/equipmentOwner', 'EquipmentOwnersController');
Route::resource('/locations', 'LocationsController');


Route::get('/locations', 'LocationsController@index')->middleware('auth');
//Route::get('/locations/create', 'LocationsController@create')->middleware('auth');
//Route::get('locations/{locations} ', 'LocationsController@update')->middleware('auth');
//Route::get('locations/{locations}/edit ', 'LocationsController@edit')->middleware('auth');
//Route::get('locations/{locations} ', 'LocationsController@destroy')->middleware('auth');

Route::get('/employees', 'EmployeesController@index')->middleware('auth');
//Route::get('/employees/create', 'EmployeesController@create')->middleware('auth');
//Route::get('/employees/{employees}', 'EmployeesController@update')->middleware('auth');
//Route::get('/employees/{employees}', 'EmployeesController@update')->middleware('auth');
//Route::get('/employees/{employees}', 'EmployeesController@destroy')->middleware('auth');
//Route::get('/employees/{employees}/edit', 'EmployeesController@edit')->middleware('auth');


Route::get('/equipment', 'EquipmentsController@index')->middleware('auth');


Route::get('/equipmentOwner', 'EquipmentOwnersController@index')->middleware('auth');

//Route::get('/equipmentOwner/create', 'EquipmentOwnersController@edit')->middleware('IsAdmin');

Route::resource('/users', 'UsersController');

app/Employee.php
<?php

namespace App;
use App\Location;
use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    protected $fillable = ['name', 'location_id'];


    public function location(){

        return $this->belongsTo('App\Location', 'location_id');

    }


}

app/Http/Controllers/EmployeesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Employee;
use App\Location;

class EmployeesController extends Controller
{

    public function index()
    {
        $employees = Employee::all();
        return view('employees.index', compact('employees'));
    }

    public function create()
    {
        $locations = Location::all(['id', 'name']);

        return view('employees.create', compact('locations'));
    }


    public function store(Request $request)
    {
        $this->validate($request, [
            'name'=>'required|max:50',
        ]);

        $employee = new Employee;
        $employee->name = $request->name;
        $employee->location_id = $request->location_id;
        $employee->save();

        return redirect('/employees');


    }


    public function show($id)
    {
        //
    }


    public function edit($id)
    {
        $employee = Employee::findOrFail($id);
        $locations = Location::all(['id', 'name']);

        return view('employees.edit', compact('employee', 'locations'));
    }


    public function update(Request $request, $id)
    {
        $employee = Employee::findOrFail($id);

        $employee->update($request->all());
        return redirect('employees');
    }

    public function destroy($id)
    {
        $employee = Employee::findOrFail($id);

        $employee->delete();

        return redirect('employees');
    }
}

resources/views/employees/create.blade.php
@extends ('layouts.admin')

@section('content')

    <div class="col-md-6 col-md-offset-3">
        <div class="box-body">
            <div class="panel panel-default">
                <div class="panel-heading"></div>
                <div class="panel-body">
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif

                    {!! Form::open(['method'=>'POST', 'action'=>'EmployeesController@store']) !!}
                    {{csrf_field()}}


                    {!! Form::label('name', 'Ime zaposlenika') !!}
                    {!! Form::text('name', null, ['class'=>'form-control']) !!}


                    <div class="form-group">
                        {!! Form::Label('name', 'Lokacija') !!}
                        <select class="form-control" name="location_id">
                            @foreach($locations as $location)
                                <option value="{{$location->id}}">{{$location->name}}</option>
                            @endforeach
                        </select>
                    </div>

                    {!! Form::submit('Dodaj', ['class'=>'btn btn-primary center-block btn-style']) !!}
                    {!! Form::close() !!}

                </div>
            </div>
        </div>
    </div>




@endsection('footer')

resources/views/employees/edit.blade.php
@extends ('layouts.admin')

@section('content')
    <div class="col-md-8 col-md-offset-2">
        <div class="box-body">
            <div class="panel panel-default">
                <div class="panel-heading"></div>
                <div class="panel-body">

                    {!! Form::model($employee,['method'=>'PATCH', 'action'=>['EmployeesController@update', $employee->id]]) !!}
                    {{csrf_field()}}

                    {!! Form::label('name', 'Ime zaposlenika') !!}

                    {!! Form::text('name', null, ['class'=>'form-control']) !!}

                    <div class="form-group">
                        {!! Form::Label('name', 'Lokacija') !!}
                        <select class="form-control" name="location_id">
                            @foreach($locations as $location)
                                <option value="{{$location->id}}"
                                @if ($employee->location->name ==$location->name )
                                    {{ 'selected' }}
                                        @endif
                                >{{$location->name}}</option>
                            @endforeach
                        </select>
                    </div>

                    {!! Form::submit('Pohrani promjene', ['class'=>'btn btn-primary center-block btn-style']) !!}

                    {!! Form::close() !!}

                    {!! Form::open(['method'=>'DELETE', 'action'=>['EmployeesController@destroy', $employee->id]]) !!}
                    {{csrf_field()}}

                    {!! Form::submit('Ukloni zaposlenika', ['class'=>'btn btn-danger pull-right']) !!}

                    {!! Form::close() !!}

                </div>
            </div>
        </div>
    </div>


@endsection('footer')

resources/views/employees/index.blade.php
@extends ('layouts.admin')

@section('content')
    <div class="col-md-10 col-md-offset-1">
        <div class="box-body">
            <div class="panel panel-default">
                <div class="panel-heading">Zaposlenik</div>
                <div class="panel-body">
                    <table class="table table-bordered table-hover dtable">
                        <thead align="center">
                        <tr>
                            <th>Ime zaposlenika</th>
                            <th>Lokacija zaposlenika</th>
                            @if(Auth::user()->role == "Administrator")
                                <th></th>
                                <th></th>
                            @endif
                        </tr>
                        </thead>
                        <tbody>

                        @foreach($employees as $employee)

                            <tr>
                                <td>{{$employee->name}}</td>
                                <td>{{$employee->location->name ?? '*Lokacija uklonjena'}}</td>
                                @if(Auth::user()->role == "Administrator")
                                    <td><div class="text-center" ><a href="{{route('employees.edit', $employee->id)}}"><i class="glyphicon glyphicon-edit"></i></a></div></td>
                                    <td><div class="text-center" ><a href="{{route('employees.destroy', $employee->id)}}"><i class="glyphicon glyphicon-trash"></i></a></div></td>
                                @endif
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                    @if(Auth::user()->role == "Administrator")
                        <button type="submit" class="btn btn-primary center-block btn-style"><a style="color: white" href="{{route('employees.create')}}">Dodaj zaposlenika</a></button>
                    @endif
                </div>
            </div>
        </div>
    </div>



@stop

@extends('layouts.footer')